#!/bin/sh

set -e

# Start only when lo is configured
if [ "$IFACE" != '--all' ]; then
	exit 0
fi

# Only run from ifup/ifdown.
case "$MODE" in
	start|stop) ;;
	*) exit 0 ;;
esac

netconf_data_dir='@root@/etc/netconf' \
	exec >/dev/null 2>&1 @target@/netctl/bin/netconf "$MODE"
